# Generated by Django 4.1.7 on 2023-02-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE VIEW timetracking_projectdurationpermonthview AS
                SELECT
                    row_number() OVER () AS id,
                    strftime('%Y', timetracking_event.date) AS year,
                    strftime('%m', timetracking_event.date) AS month,
                    timetracking_event.project_id AS project_id,
                    sum(timetracking_event.duration) AS total_duration
                FROM timetracking_event
                GROUP BY year, month, project_id;
            """,
            reverse_sql="""
                DROP VIEW timetracking_projectdurationpermonthview;
            """,
        ),
        migrations.CreateModel(
            name="ProjectDurationPerMonthView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("year", models.CharField(max_length=4, verbose_name="year")),
                ("month", models.CharField(max_length=2, verbose_name="month")),
                ("total_duration", models.DurationField(verbose_name="total duration")),
            ],
            options={
                "managed": False,
            },
        ),
    ]
